server:
  port: 80



spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    #监控统计拦截的filters
    filter: stat
    #mysql驱动
    driver:  com.mysql.cj.jdbc.Driver
    #基本属性
    url: jdbc:mysql://127.0.0.1:3306/ymkj_app?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: szhzs918918
    #配置初始化大小/最小/最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000





  #devtools插件
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署

